unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-v

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Pane resizing
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Break pane into new window (hide) and join pane from window (show)
bind-key b break-pane -d  # Break pane to a new window
bind-key t choose-window 'join-pane -h -s "%%"'  # Join pane horizontally from selected window
bind-key T choose-window 'join-pane -v -s "%%"'  # Join pane vertically from selected window

set-option -g status-position bottom

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'arcticicestudio/nord-tmux'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# For Pi coding agent
set -g extended-keys on
set -g extended-keys-format csi-u
